### ISSUE TITLE
[?] External build profile

### ISSUE THREAD

**Issue by tavlima** [sbt/sbt-rjs#46]
How am I supposed to supply an external build.js file, for instance? Can I (somehow) configure sbt-rjs to use an external build profile or I really have to translate everything to scala JS.Object syntax?

Thanks in advance

**Comment by yanns** [comment]
@huntc in some projects, the build profile is already defined within an JavaScript file, like main.build.js.

It would be great if we can read this file to import the build profile. 
We maybe need a implicit conversion from a path to a JS.Object for this.
