### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt-rjs#64]
@huntc @jamesward would you be able to cut a new release?

**Comment by jamesward** [comment]
I think that'd have to be @huntc or @jroper.

**Comment by huntc** [comment]
I will do it

**Comment by huntc** [comment]
Sorry I didn't get to this yesterday. I need to make a few changes so that it will release to the new bintray repo. I need an hour to fix everything. Hopefully today.

**Comment by huntc** [comment]
1.0.8 is now published.

**Comment by benmccann** [comment]
thanks!
