### ISSUE TITLE
SbtRjs does not compile against sbt-web 1.4.0

### ISSUE THREAD

**Issue by growak** [sbt/sbt-rjs#66]
The syncMappings method signature has changed with the new cacheName argument with lead to a NoSuchMethodError when using sbt-rjs with sbt-web 1.4.0.

**Comment by growak** [comment]
sbt scripted works on my local machine but fails on travis.

**Comment by alaz** [comment]
This is a bummer for using Play as a web framework. Apparently no one is using Play as such.

**Comment by danielnixon** [comment]
Fixed in [my fork](https://github.com/danielnixon/sbt-rjs). Try `addSbtPlugin("org.danielnixon" % "sbt-rjs" % "1.0.9")`.

**Comment by benmccann** [comment]
Fixed
