### ISSUE TITLE
Cross build for sbt 0.13 and 1.0

### ISSUE THREAD

**Issue by marcospereira** [sbt/sbt-rjs#81]

**Comment by benmccann** [comment]
PR here: https://github.com/sbt/sbt-rjs/pull/82

**Comment by benmccann** [comment]
PR merged. Someone will still need to cut a release

**Comment by marcospereira** [comment]
Thank you, @benmccann.

I will keep this open until we cut a release.

**Comment by marcospereira** [comment]
Also #83.

**Comment by domdorn** [comment]
Hi!

Whats necessary to cut a release? Can I help somehow? sbt-rjs is the only thing left for getting my project to sbt 1.0.2

**Comment by ikr0m** [comment]
I hope you guys find a time to cut a release soon. This one is blocking migration to sbt 1.0.2

**Comment by gpgekko** [comment]
@ikr0m I think they actually just released a version yesterday ([1.0.10](https://github.com/sbt/sbt-rjs/releases/tag/1.0.10)) with support for this.

**Comment by ikr0m** [comment]
@gpgekko Great! Now it's working with sbt 1.0.2. Thank you!

**Comment by marcospereira** [comment]
1.0.10 was released as pointed out by @gpgekko.

Closing.
